---
services:
  zookeeper:
    container_name: zookeeper-cntr
    restart: always
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_4LW_COMMANDS_WHITELIST=ruok

    networks:
      - flight_network
    healthcheck:
      test: echo ruok | nc localhost 2181 | grep imok || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

  kafka:
    container_name: kafka-cntr
    restart: always
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - flight_network
    healthcheck:
      test: /opt/bitnami/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9093 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

  spark-master:
    image: ${CI_REGISTRY_IMAGE}/flight-dash-spark:${IMAGE_VERSION}
    build:
      context: ./ 
      dockerfile: spark/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: spark-master
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    deploy: 
      resources:
        limits:
          cpus: '2'
    networks:
      - flight_network
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

  spark-worker-1:
    image: ${CI_REGISTRY_IMAGE}/flight-dash-spark:${IMAGE_VERSION}
    container_name: spark-worker-1
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      spark-master: 
        condition: service_healthy
    ports:
      - "8081:8081"   # Web UI for Spark Worker 
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - flight_network
    healthcheck:
      test: curl --fail http://localhost:8081 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

  spark-worker-2:
    image: ${CI_REGISTRY_IMAGE}/flight-dash-spark:${IMAGE_VERSION}
    container_name: spark-worker-2
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      spark-master:
        condition: service_healthy
    ports:
      - "8082:8081"   # Web UI for Spark Worker 
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - flight_network
    healthcheck:
      test: curl --fail http://localhost:8081 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

  spark-job-submit:
    image: ${CI_REGISTRY_IMAGE}/flight-dash-spark:${IMAGE_VERSION}
    container_name: spark-job-submit
    depends_on:
      spark-master:
        condition: service_healthy
      spark-worker-1:
        condition: service_healthy
      spark-worker-2:
        condition: service_healthy
      kafka:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      - HADOOP_USER_NAME=spark
    entrypoint: ["/opt/bitnami/spark/bin/spark-submit",
                 "--master", "spark://spark-master:7077",
                 "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.4,org.apache.kafka:kafka-clients:3.2.3,org.elasticsearch:elasticsearch-spark-30_2.12:8.8.2,commons-httpclient:commons-httpclient:3.1",
                 "--total-executor-cores", "2",
                 "--executor-memory", "2g",
                 "/opt/bitnami/spark/spark_stream.py"]
    networks:
      - flight_network

  elasticsearch:
    image: ${CI_REGISTRY_IMAGE}/flight-dash-elasticsearch:${IMAGE_VERSION}
    container_name: elasticsearch-cntr
    build:
      context: .
      dockerfile: elasticsearch/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - cluster.name=kafka-cluster
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/bitnami/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      kafka:
        condition: service_healthy
    stdin_open: true
    tty: true
    restart: always
    networks:
      - flight_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
    healthcheck:
      test: curl -u elastic:elastic -s -f elasticsearch-cntr:9200/_cat/health >/dev/null || exit 1
      interval: 10s
      timeout: 15s
      retries: 5

  kibana:
    image: ${CI_REGISTRY_IMAGE}/flight-dash-kibana:${IMAGE_VERSION}
    container_name: kibana-cntr
    build:
      context: .
      dockerfile: kibana/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    stdin_open: true
    tty: true
    restart: always
    networks:
      - flight_network
    links: ['elasticsearch']
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
    healthcheck:
      test: curl --fail http://kibana-cntr:5601 || exit 1
      interval: 30s
      retries: 3
      timeout: 30s   

  mongo:
    container_name: mongo-cntr
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks: 
      - flight_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: bash -c "</dev/tcp/localhost/27017" || exit 1
      interval: 10s
      timeout: 10s
      retries: 3


  backend:
    image: ${CI_REGISTRY_IMAGE}/flight-dash-backend:${IMAGE_VERSION}
    container_name: backend-cntr
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_TEST_URI=${MONGO_TEST_URI}
      - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - API_URL=${API_URL}
      - SECRET_KEY=${SECRET_KEY}
      - PORT=${PORT}
    depends_on:
      mongo:
        condition: service_healthy 
      kafka:
        condition: service_healthy
    networks:
      - flight_network
    healthcheck:
      test: curl --fail http://localhost:3000/live || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    image: ${CI_REGISTRY_IMAGE}/flight-dash-frontend:${IMAGE_VERSION}
    container_name: frontend-cntr
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      backend:
        condition: service_healthy
    networks: 
      - flight_network
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 10s
      timeout: 8s
      retries: 3

networks:
  flight_network:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
  mongo_data:
    driver: local  