apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    http:
      port: "9200"
    path:
      data: /bitnami/elasticsearch/data
    transport:
      port: "9300"
    network:
      host: 0.0.0.0
    discovery:
      seed_hosts:
        - elasticsearch-0.elasticsearch
        # - elasticsearch-1.elasticsearch
    cluster:
      initial_master_nodes:
        - elasticsearch-0
        # - elasticsearch-1
      name: kafka-cluster
    xpack:
      security:
        enabled: "false"
      ml:
        enabled: "false"
