apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-checkpoints-pvc
spec:
  accessModes:
    - ReadWriteOnce   # Or ReadWriteMany if needed
  resources:
    requests:
      storage: 4Gi
